apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
      tier: sprint-6
      role: app
  template:
    metadata:
      labels:
        app: test-app
        tier: sprint-6
        role: app
    spec:
      containers:
      - name: test-app
        image: shestera/scaletestapp
        resources:
          requests:
            cpu: 30m
            memory: 30Mi
          limits:
            cpu: 30m
            memory: 30Mi
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: test-app-sprint-6
  namespace: default
  labels:
    app: test-app
    tier: sprint-6
    role: app
spec:
  type: NodePort
  selector:
    app: test-app
    tier: sprint-6
    role: app
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: test-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: test-app
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 10
